### ISSUE TITLE
Lower minimum version for Faraday to increase compatibility

### ISSUE THREAD

**Issue by rkischuk** [ringcentral/ringcentral-ruby#1]
Faraday is required with a minimum version of 0.13

Some other gems (such as `oauth`)  in our projects require the version to be <= 0.10, so we couldn't start working with this gem.

I forked the project and used a requirement of Faraday 0.10 and there don't seem to be any negative consequences.

**Comment by tylerlong** [comment]
I released a new version which requires Faraday >= 0.10.0
