### ISSUE TITLE
Gemfile compatibility issues

### ISSUE THREAD

**Issue by patricksimpson** [ringcentral/ringcentral-ruby#17]
Recent gem updates fails to resolve dependency issues:

```
Could not find compatible versions

Because every version of ringcentral-sdk depends on pubnub >= 5.0.0, < 6.A
  and pubnub >= 4.1.5 depends on concurrent-ruby ~> 1.1.5,
  every version of ringcentral-sdk requires concurrent-ruby ~> 1.1.5.
```

**Comment by patricksimpson** [comment]
Looks like PubNub is currently deprecated. 🦖

**Comment by minimul** [comment]
+1 We can't install the later versions (`>= 0.9.8') of this gem because of the concurrent-ruby version clash.

@patricksimpson I've also submitted this https://github.com/ringcentral/ringcentral-ruby/pull/19 that'll fix this issue without total removal, which I don't think they are ready to do yet.

**Comment by tylerlong** [comment]
PubNub has been removed.
