### ISSUE TITLE
Name collision with `ringcentral` gem

### ISSUE THREAD

**Issue by grokify** [ringcentral/ringcentral-ruby#2]
**Problem**

If you have both the `ringcentral` and `ringcentral-sdk` gems installed, you will run into a collision error when attempting to initialize the `ringcentral-sdk` RingCentral SDK:

```
undefined method `new' for RingCentral:Module (NoMethodError)
```

This occurs because both gems use the `ringcentral` namespace, e.g. `require 'ringcentral'`

Check this by running gem list:

```
$ gem list | grep -i ringcentral
ringcentral (0.2.0)
ringcentral-sdk (0.8.1, 0.5.0)
```

**Solution**

In this case, uninstall the legacy gem and then the new gem will run as expected.

```
$ gem uninstall ringcentral
```

Everyone is recommended to move to the REST API and no longer use the legacy API so the legacy API SDK should not be needed.

**Comment by tylerlong** [comment]
I will add this to readme followed by closing this issue.

**Comment by tylerlong** [comment]
Done
